.TH "Binance" 3 "Sun Apr 15 2018" "PHP Binance Api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Binance \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAPI\fP"
.br
.RI "\fIMain Binance class\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Binance Api from the source code\&.
