.TH "Binance\API" 3 "Sun Apr 22 2018" "PHP Binance Api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Binance\API \- 
.PP
Main Binance class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.RI "\fIConstructor for the class, send as many agument as you want\&. \fP"
.ti -1c
.RI "\fB__get\fP (string $member)"
.br
.RI "\fImagic get for private and protected members \fP"
.ti -1c
.RI "\fB__set\fP (string $member, $value)"
.br
.RI "\fImagic set for private and protected members \fP"
.ti -1c
.RI "\fBbuy\fP (string $symbol, $quantity, $price, string $type='LIMIT', array $flags=[])"
.br
.RI "\fIbuy attempts to create a currency order each currency supports a number of order types, such as -LIMIT -MARKET -STOP_LOSS -STOP_LOSS_LIMIT -TAKE_PROFIT -TAKE_PROFIT_LIMIT -LIMIT_MAKER \fP"
.ti -1c
.RI "\fBbuyTest\fP (string $symbol, $quantity, $price, string $type='LIMIT', array $flags=[])"
.br
.RI "\fIbuyTest attempts to create a TEST currency order \fP"
.ti -1c
.RI "\fBsell\fP (string $symbol, $quantity, $price, string $type='LIMIT', array $flags=[])"
.br
.RI "\fIsell attempts to create a currency order each currency supports a number of order types, such as -LIMIT -MARKET -STOP_LOSS -STOP_LOSS_LIMIT -TAKE_PROFIT -TAKE_PROFIT_LIMIT -LIMIT_MAKER \fP"
.ti -1c
.RI "\fBsellTest\fP (string $symbol, $quantity, $price, string $type='LIMIT', array $flags=[])"
.br
.RI "\fIsellTest attempts to create a TEST currency order \fP"
.ti -1c
.RI "\fBmarketBuy\fP (string $symbol, $quantity, array $flags=[])"
.br
.RI "\fImarketBuy attempts to create a currency order at given market price \fP"
.ti -1c
.RI "\fBmarketBuyTest\fP (string $symbol, $quantity, array $flags=[])"
.br
.RI "\fImarketBuyTest attempts to create a TEST currency order at given market price \fP"
.ti -1c
.RI "\fBmarketSell\fP (string $symbol, $quantity, array $flags=[])"
.br
.RI "\fImarketSell attempts to create a currency order at given market price \fP"
.ti -1c
.RI "\fBmarketSellTest\fP (string $symbol, $quantity, array $flags=[])"
.br
.RI "\fImarketSellTest attempts to create a TEST currency order at given market price \fP"
.ti -1c
.RI "\fBcancel\fP (string $symbol, $orderid)"
.br
.RI "\fIcancel attempts to cancel a currency order \fP"
.ti -1c
.RI "\fBorderStatus\fP (string $symbol, $orderid)"
.br
.RI "\fIorderStatus attempts to get orders status \fP"
.ti -1c
.RI "\fBopenOrders\fP (string $symbol=null)"
.br
.RI "\fIopenOrders attempts to get open orders for all currencies or a specific currency \fP"
.ti -1c
.RI "\fBorders\fP (string $symbol, int $limit=500, int $fromOrderId=1)"
.br
.RI "\fIorders attempts to get the orders for all or a specific currency \fP"
.ti -1c
.RI "\fBhistory\fP (string $symbol, int $limit=500, int $fromTradeId=-1)"
.br
.RI "\fIhistory Get the complete account trade history for all or a specific currency \fP"
.ti -1c
.RI "\fBuseServerTime\fP ()"
.br
.RI "\fIuseServerTime adds the 'useServerTime'=>true to the API request to avoid time errors \fP"
.ti -1c
.RI "\fBtime\fP ()"
.br
.RI "\fItime Gets the server time \fP"
.ti -1c
.RI "\fBexchangeInfo\fP ()"
.br
.RI "\fIexchangeInfo Gets the complete exchange info, including limits, currency options etc\&. \fP"
.ti -1c
.RI "\fBwithdraw\fP (string $asset, string $address, $amount, $addressTag=null)"
.br
.RI "\fIwithdraw requests a asset be withdrawn from binance to another wallet \fP"
.ti -1c
.RI "\fBdepositAddress\fP (string $asset)"
.br
.RI "\fIdepositAddress get the deposit address for an asset \fP"
.ti -1c
.RI "\fBdepositHistory\fP (string $asset=null, array $params=[])"
.br
.RI "\fIdepositAddress get the deposit history for an asset \fP"
.ti -1c
.RI "\fBwithdrawHistory\fP (string $asset=null, array $params=[])"
.br
.RI "\fIwithdrawHistory get the withdrawal history for an asset \fP"
.ti -1c
.RI "\fBwithdrawFee\fP (string $asset)"
.br
.RI "\fIwithdrawFee get the withdrawal fee for an asset \fP"
.ti -1c
.RI "\fBprices\fP ()"
.br
.RI "\fIprices get all the current prices \fP"
.ti -1c
.RI "\fBbookPrices\fP ()"
.br
.RI "\fIbookPrices get all bid/asks prices \fP"
.ti -1c
.RI "\fBaccount\fP ()"
.br
.RI "\fIaccount get all information about the api account \fP"
.ti -1c
.RI "\fBprevDay\fP (string $symbol=null)"
.br
.RI "\fIprevDay get 24hr ticker price change statistics for symbols \fP"
.ti -1c
.RI "\fBaggTrades\fP (string $symbol)"
.br
.RI "\fIaggTrades get Market History / Aggregate Trades \fP"
.ti -1c
.RI "\fBdepth\fP (string $symbol)"
.br
.RI "\fIdepth get Market depth \fP"
.ti -1c
.RI "\fBbalances\fP ($priceData=false)"
.br
.RI "\fIbalances get balances for the account assets \fP"
.ti -1c
.RI "\fBgetProxyUriString\fP ()"
.br
.RI "\fIgetProxyUriString get Uniform Resource Identifier string assocaited with proxy config \fP"
.ti -1c
.RI "\fBsetProxy\fP (array $proxyconf)"
.br
.RI "\fIsetProxy set proxy config by passing in an array of the proxy configuration \fP"
.ti -1c
.RI "\fBorder\fP (string $side, string $symbol, $quantity, $price, string $type='LIMIT', array $flags=[], bool $test=false)"
.br
.RI "\fIorder formats the orders before sending them to the curl wrapper function You can call this function directly or use the helper functions \fP"
.ti -1c
.RI "\fBcandlesticks\fP (string $symbol, string $interval='5m', int $limit=null, $startTime=null, $endTime=null)"
.br
.RI "\fIcandlesticks get the candles for the given intervals 1m,3m,5m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M \fP"
.ti -1c
.RI "\fBcumulative\fP (array $\fBdepth\fP)"
.br
.RI "\fIcumulative Converts depth cache into a cumulative array \fP"
.ti -1c
.RI "\fBhighstock\fP (array $\fBchart\fP, bool $include_volume=false)"
.br
.RI "\fIhighstock Converts Chart Data into array for highstock & kline charts \fP"
.ti -1c
.RI "\fBfirst\fP (array $array)"
.br
.RI "\fIfirst Gets first key of an array \fP"
.ti -1c
.RI "\fBlast\fP (array $array)"
.br
.RI "\fIlast Gets last key of an array \fP"
.ti -1c
.RI "\fBdisplayDepth\fP (array $array)"
.br
.RI "\fIdisplayDepth Formats nicely for console output \fP"
.ti -1c
.RI "\fBgetTransfered\fP ()"
.br
.RI "\fIgetTransfered gets the total transfered in b,Kb,Mb,Gb \fP"
.ti -1c
.RI "\fBgetRequestCount\fP ()"
.br
.RI "\fIgetRequestCount gets the total number of API calls \fP"
.ti -1c
.RI "\fBaddToTransfered\fP (int $int)"
.br
.RI "\fIaddToTransfered add interger bytes to the total transfered also incrementes the api counter \fP"
.ti -1c
.RI "\fBsortDepth\fP (string $symbol, int $limit=11)"
.br
.RI "\fIsortDepth Sorts depth data for display & getting highest bid and lowest ask \fP"
.ti -1c
.RI "\fBdepthCache\fP ($symbols, callable $callback)"
.br
.RI "\fIdepthCache Pulls /depth data and subscribes to  WebSocket endpoint Maintains a local Depth Cache in sync via lastUpdateId\&. \fP"
.ti -1c
.RI "\fBtrades\fP ($symbols, callable $callback)"
.br
.RI "\fItrades Trades WebSocket Endpoint \fP"
.ti -1c
.RI "\fBticker\fP ($symbol, callable $callback)"
.br
.RI "\fIticker pulls 24h price change statistics via WebSocket \fP"
.ti -1c
.RI "\fBchart\fP ($symbols, string $interval='30m', callable $callback)"
.br
.RI "\fIchart Pulls /kline data and subscribes to  WebSocket endpoint \fP"
.ti -1c
.RI "\fBkline\fP ($symbols, string $interval='30m', callable $callback)"
.br
.RI "\fIkline Subscribes to  WebSocket endpoint for latest chart data only \fP"
.ti -1c
.RI "\fBterminate\fP ($endpoint)"
.br
.RI "\fIterminate Terminates websocket endpoints\&. \fP"
.ti -1c
.RI "\fBkeepAlive\fP ()"
.br
.RI "\fIkeepAlive Keep-alive function for userDataStream \fP"
.ti -1c
.RI "\fBuserData\fP (&$balance_callback, &$execution_callback=false)"
.br
.RI "\fIuserData Issues userDataStream token and keepalive, subscribes to userData WebSocket \fP"
.ti -1c
.RI "\fBminiTicker\fP (callable $callback)"
.br
.RI "\fIminiTicker Get miniTicker for all symbols \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$base\fP = 'https://api\&.binance\&.com/api/'"
.br
.ti -1c
.RI "\fB$wapi\fP = 'https://api\&.binance\&.com/wapi/'"
.br
.ti -1c
.RI "\fB$stream\fP = 'wss://stream\&.binance\&.com:9443/ws/'"
.br
.ti -1c
.RI "\fB$api_key\fP"
.br
.ti -1c
.RI "\fB$api_secret\fP"
.br
.ti -1c
.RI "\fB$depthCache\fP = []"
.br
.ti -1c
.RI "\fB$depthQueue\fP = []"
.br
.ti -1c
.RI "\fB$chartQueue\fP = []"
.br
.ti -1c
.RI "\fB$charts\fP = []"
.br
.ti -1c
.RI "\fB$curlOpts\fP = []"
.br
.ti -1c
.RI "\fB$info\fP"
.br
.ti -1c
.RI "\fB$proxyConf\fP = null"
.br
.ti -1c
.RI "\fB$transfered\fP = 0"
.br
.ti -1c
.RI "\fB$requestCount\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main Binance class\&. 

Eg\&. Usage: require 'vendor/autoload\&.php'; $api = new Binance\\API(); 
.PP
Definition at line 29 of file php-binance-api\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Binance\\API::__construct ()"

.PP
Constructor for the class, send as many agument as you want\&. 
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.PP
Definition at line 60 of file php-binance-api\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "Binance\\API::__get (string$member)"

.PP
magic get for private and protected members 
.PP
\fBParameters:\fP
.RS 4
\fI$file\fP string the name of the property to return 
.RE
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.PP
Definition at line 171 of file php-binance-api\&.php\&.
.SS "Binance\\API::__set (string$member, $value)"

.PP
magic set for private and protected members 
.PP
\fBParameters:\fP
.RS 4
\fI$member\fP string the name of the member property 
.br
\fI$value\fP the value of the member property 
.RE
.PP

.PP
Definition at line 185 of file php-binance-api\&.php\&.
.SS "Binance\\API::account ()"

.PP
account get all information about the api account $account = $api->account();
.PP
\fBReturns:\fP
.RS 4
array with error message or array of all the account information 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 724 of file php-binance-api\&.php\&.
.SS "Binance\\API::addToTransfered (int$int)"

.PP
addToTransfered add interger bytes to the total transfered also incrementes the api counter $apiCount = $api->addToTransfered( $int );
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.PP
Definition at line 1555 of file php-binance-api\&.php\&.
.SS "Binance\\API::aggTrades (string$symbol)"

.PP
aggTrades get Market History / Aggregate Trades $trades = $api->aggTrades('BNBBTC');
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the symbol to get the trade information for 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or array of market history 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 758 of file php-binance-api\&.php\&.
.SS "Binance\\API::balances ($priceData = \fCfalse\fP)"

.PP
balances get balances for the account assets $balances = $api->balances($ticker);
.PP
\fBParameters:\fP
.RS 4
\fI$priceData\fP array of the symbols balances are required for 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or array of balances 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 799 of file php-binance-api\&.php\&.
.SS "Binance\\API::bookPrices ()"

.PP
bookPrices get all bid/asks prices $ticker = $api->bookPrices();
.PP
\fBReturns:\fP
.RS 4
array with error message or array of all the book prices 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 711 of file php-binance-api\&.php\&.
.SS "Binance\\API::buy (string$symbol, $quantity, $price, string$type = \fC'LIMIT'\fP, array$flags = \fC[]\fP)"

.PP
buy attempts to create a currency order each currency supports a number of order types, such as -LIMIT -MARKET -STOP_LOSS -STOP_LOSS_LIMIT -TAKE_PROFIT -TAKE_PROFIT_LIMIT -LIMIT_MAKER You should check the 
.PP
\fBSee Also:\fP
.RS 4
exchangeInfo for each currency to determine what types of orders can be placed against specific pairs
.RE
.PP
$quantity = 1; $price = 0\&.0005; $order = $api->buy('BNBBTC', $quantity, $price);
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$quantity\fP string the quantity required 
.br
\fI$price\fP string price per unit you want to spend 
.br
\fI$type\fP string type of order 
.br
\fI$flags\fP array addtional options for order type 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or the order details 
.RE
.PP

.PP
Definition at line 298 of file php-binance-api\&.php\&.
.SS "Binance\\API::buyTest (string$symbol, $quantity, $price, string$type = \fC'LIMIT'\fP, array$flags = \fC[]\fP)"

.PP
buyTest attempts to create a TEST currency order 
.PP
\fBSee Also:\fP
.RS 4
buy()
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$quantity\fP string the quantity required 
.br
\fI$price\fP string price per unit you want to spend 
.br
\fI$type\fP string config 
.br
\fI$flags\fP array config 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or empty or the order details 
.RE
.PP

.PP
Definition at line 315 of file php-binance-api\&.php\&.
.SS "Binance\\API::cancel (string$symbol, $orderid)"

.PP
cancel attempts to cancel a currency order $orderid = '123456789'; $order = $api->cancel('BNBBTC', $orderid);
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$orderid\fP string the orderid to cancel 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or the order details 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 440 of file php-binance-api\&.php\&.
.SS "Binance\\API::candlesticks (string$symbol, string$interval = \fC'5m'\fP, int$limit = \fCnull\fP, $startTime = \fCnull\fP, $endTime = \fCnull\fP)"

.PP
candlesticks get the candles for the given intervals 1m,3m,5m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M $candles = $api->candlesticks('BNBBTC', '5m');
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string to query 
.br
\fI$interval\fP string to request 
.br
\fI$limit\fP int limit the amount of candles 
.br
\fI$startTime\fP string request candle information starting from here 
.br
\fI$endTime\fP string request candle information ending here 
.RE
.PP
\fBReturns:\fP
.RS 4
array containing the response 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 1065 of file php-binance-api\&.php\&.
.SS "Binance\\API::chart ($symbols, string$interval = \fC'30m'\fP, callable$callback)"

.PP
chart Pulls /kline data and subscribes to  WebSocket endpoint $api->chart(['BNBBTC'], '15m', function($api, $symbol, $chart) { echo '{$symbol} chart update\\n'; print_r($chart); });
.PP
\fBParameters:\fP
.RS 4
\fI$symbols\fP string required symbols 
.br
\fI$interval\fP string time inteval 
.br
\fI$callback\fP callable closure 
.RE
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 1874 of file php-binance-api\&.php\&.
.SS "Binance\\API::cumulative (array$depth)"

.PP
cumulative Converts depth cache into a cumulative array $cumulative = $api->cumulative($depth);
.PP
\fBParameters:\fP
.RS 4
\fI$depth\fP array cache array 
.RE
.PP
\fBReturns:\fP
.RS 4
array cumulative depth cache 
.RE
.PP

.PP
Definition at line 1373 of file php-binance-api\&.php\&.
.SS "Binance\\API::depositAddress (string$asset)"

.PP
depositAddress get the deposit address for an asset $depositAddress = $api->depositAddress('VEN');
.PP
\fBParameters:\fP
.RS 4
\fI$asset\fP string the currency such as BTC 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or array deposit address information 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 621 of file php-binance-api\&.php\&.
.SS "Binance\\API::depositHistory (string$asset = \fCnull\fP, array$params = \fC[]\fP)"

.PP
depositAddress get the deposit history for an asset $depositHistory = $api->depositHistory();
.PP
$depositHistory = $api->depositHistory( 'BTC' );
.PP
\fBParameters:\fP
.RS 4
\fI$asset\fP string empty or the currency such as BTC 
.br
\fI$params\fP array optional startTime, endTime, status parameters 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or array deposit history information 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 642 of file php-binance-api\&.php\&.
.SS "Binance\\API::depth (string$symbol)"

.PP
depth get Market depth $depth = $api->depth('ETHBTC');
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the symbol to get the depth information for 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or array of market depth 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 774 of file php-binance-api\&.php\&.
.SS "Binance\\API::depthCache ($symbols, callable$callback)"

.PP
depthCache Pulls /depth data and subscribes to  WebSocket endpoint Maintains a local Depth Cache in sync via lastUpdateId\&. See depth() and depthHandler()
.PP
$api->depthCache(['BNBBTC'], function($api, $symbol, $depth) { echo '{$symbol} depth cache update'\&.PHP_EOL; //print_r($depth); // Print all depth data $limit = 11; // Show only the closest asks/bids $sorted = $api->sortDepth($symbol, $limit); $bid = $api->first($sorted['bids']); $ask = $api->first($sorted['asks']); echo $api->displayDepth($sorted); echo 'ask: {$ask}'\&.PHP_EOL; echo 'bid: {$bid}'\&.PHP_EOL; });
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string optional array of symbols 
.br
\fI$callback\fP callable closure 
.RE
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.PP
Definition at line 1676 of file php-binance-api\&.php\&.
.SS "Binance\\API::displayDepth (array$array)"

.PP
displayDepth Formats nicely for console output $outputString = $api->displayDepth($array);
.PP
\fBParameters:\fP
.RS 4
\fI$array\fP array 
.RE
.PP
\fBReturns:\fP
.RS 4
string of the depth information 
.RE
.PP

.PP
Definition at line 1468 of file php-binance-api\&.php\&.
.SS "Binance\\API::exchangeInfo ()"

.PP
exchangeInfo Gets the complete exchange info, including limits, currency options etc\&. $info = $api->exchangeInfo();
.PP
\fBReturns:\fP
.RS 4
array with error message or exchange info array 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 572 of file php-binance-api\&.php\&.
.SS "Binance\\API::first (array$array)"

.PP
first Gets first key of an array $first = $api->first($array);
.PP
\fBParameters:\fP
.RS 4
\fI$array\fP array 
.RE
.PP
\fBReturns:\fP
.RS 4
string key or null 
.RE
.PP

.PP
Definition at line 1436 of file php-binance-api\&.php\&.
.SS "Binance\\API::getProxyUriString ()"

.PP
getProxyUriString get Uniform Resource Identifier string assocaited with proxy config $balances = $api->getProxyUriString();
.PP
\fBReturns:\fP
.RS 4
string uri 
.RE
.PP

.PP
Definition at line 815 of file php-binance-api\&.php\&.
.SS "Binance\\API::getRequestCount ()"

.PP
getRequestCount gets the total number of API calls $apiCount = $api->getRequestCount();
.PP
\fBReturns:\fP
.RS 4
int get the total number of api calls 
.RE
.PP

.PP
Definition at line 1542 of file php-binance-api\&.php\&.
.SS "Binance\\API::getTransfered ()"

.PP
getTransfered gets the total transfered in b,Kb,Mb,Gb $transfered = $api->getTransfered();
.PP
\fBReturns:\fP
.RS 4
string showing the total transfered 
.RE
.PP

.PP
Definition at line 1522 of file php-binance-api\&.php\&.
.SS "Binance\\API::highstock (array$chart, bool$include_volume = \fCfalse\fP)"

.PP
highstock Converts Chart Data into array for highstock & kline charts $highstock = $api->highstock($chart, $include_volume);
.PP
\fBParameters:\fP
.RS 4
\fI$chart\fP array 
.br
\fI$include_volume\fP bool for inclusion of volume 
.RE
.PP
\fBReturns:\fP
.RS 4
array highchart data 
.RE
.PP

.PP
Definition at line 1408 of file php-binance-api\&.php\&.
.SS "Binance\\API::history (string$symbol, int$limit = \fC500\fP, int$fromTradeId = \fC-1\fP)"

.PP
history Get the complete account trade history for all or a specific currency $allHistory = $api->history(); $BNBHistory = $api->history('BNBBTC'); $limitBNBHistory = $api->history('BNBBTC',5); $limitBNBHistoryFromId = $api->history('BNBBTC',5,3);
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$limit\fP int the amount of orders returned 
.br
\fI$fromTradeId\fP int (optional) return the orders from this order onwards\&. negative for all 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or array of orderDetails array 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 522 of file php-binance-api\&.php\&.
.SS "Binance\\API::keepAlive ()"

.PP
keepAlive Keep-alive function for userDataStream $api->keepAlive();
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.PP
Definition at line 2015 of file php-binance-api\&.php\&.
.SS "Binance\\API::kline ($symbols, string$interval = \fC'30m'\fP, callable$callback)"

.PP
kline Subscribes to  WebSocket endpoint for latest chart data only $api->kline(['BNBBTC'], '15m', function($api, $symbol, $chart) { echo '{$symbol} chart update\\n'; print_r($chart); });
.PP
\fBParameters:\fP
.RS 4
\fI$symbols\fP string required symbols 
.br
\fI$interval\fP string time inteval 
.br
\fI$callback\fP callable closure 
.RE
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 1955 of file php-binance-api\&.php\&.
.SS "Binance\\API::last (array$array)"

.PP
last Gets last key of an array $last = $api->last($array);
.PP
\fBParameters:\fP
.RS 4
\fI$array\fP array 
.RE
.PP
\fBReturns:\fP
.RS 4
string key or null 
.RE
.PP

.PP
Definition at line 1452 of file php-binance-api\&.php\&.
.SS "Binance\\API::marketBuy (string$symbol, $quantity, array$flags = \fC[]\fP)"

.PP
marketBuy attempts to create a currency order at given market price $quantity = 1; $order = $api->marketBuy('BNBBTC', $quantity);
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$quantity\fP string the quantity required 
.br
\fI$flags\fP array addtional options for order type 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or the order details 
.RE
.PP

.PP
Definition at line 378 of file php-binance-api\&.php\&.
.SS "Binance\\API::marketBuyTest (string$symbol, $quantity, array$flags = \fC[]\fP)"

.PP
marketBuyTest attempts to create a TEST currency order at given market price 
.PP
\fBSee Also:\fP
.RS 4
marketBuy()
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$quantity\fP string the quantity required 
.br
\fI$flags\fP array addtional options for order type 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or the order details 
.RE
.PP

.PP
Definition at line 393 of file php-binance-api\&.php\&.
.SS "Binance\\API::marketSell (string$symbol, $quantity, array$flags = \fC[]\fP)"

.PP
marketSell attempts to create a currency order at given market price $quantity = 1; $order = $api->marketSell('BNBBTC', $quantity);
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$quantity\fP string the quantity required 
.br
\fI$flags\fP array addtional options for order type 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or the order details 
.RE
.PP

.PP
Definition at line 409 of file php-binance-api\&.php\&.
.SS "Binance\\API::marketSellTest (string$symbol, $quantity, array$flags = \fC[]\fP)"

.PP
marketSellTest attempts to create a TEST currency order at given market price 
.PP
\fBSee Also:\fP
.RS 4
marketSellTest()
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$quantity\fP string the quantity required 
.br
\fI$flags\fP array addtional options for order type 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or the order details 
.RE
.PP

.PP
Definition at line 424 of file php-binance-api\&.php\&.
.SS "Binance\\API::miniTicker (callable$callback)"

.PP
miniTicker Get miniTicker for all symbols $api->miniTicker(function($api, $ticker) { print_r($ticker); });
.PP
\fBParameters:\fP
.RS 4
\fI$callback\fP callable function closer that takes 2 arguments, $pai and $ticker data 
.RE
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.PP
Definition at line 2114 of file php-binance-api\&.php\&.
.SS "Binance\\API::openOrders (string$symbol = \fCnull\fP)"

.PP
openOrders attempts to get open orders for all currencies or a specific currency $allOpenOrders = $api->openOrders(); $allBNBOrders = $api->openOrders( 'BNBBTC' );
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or the order details 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 477 of file php-binance-api\&.php\&.
.SS "Binance\\API::order (string$side, string$symbol, $quantity, $price, string$type = \fC'LIMIT'\fP, array$flags = \fC[]\fP, bool$test = \fCfalse\fP)"

.PP
order formats the orders before sending them to the curl wrapper function You can call this function directly or use the helper functions 
.PP
\fBSee Also:\fP
.RS 4
buy() 
.PP
sell() 
.PP
marketBuy() 
.PP
marketSell() $this->httpRequest( 'https://api\&.binance\&.com/api/v1/ticker/24hr');
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$side\fP string typically 'BUY' or 'SELL' 
.br
\fI$symbol\fP string to buy or sell 
.br
\fI$quantity\fP string in the order 
.br
\fI$price\fP string for the order 
.br
\fI$type\fP string is determined by the symbol bu typicall LIMIT, STOP_LOSS_LIMIT etc\&. 
.br
\fI$flags\fP array additional transaction options 
.br
\fI$test\fP bool whether to test or not, test only validates the query 
.RE
.PP
\fBReturns:\fP
.RS 4
array containing the response 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 1003 of file php-binance-api\&.php\&.
.SS "Binance\\API::orders (string$symbol, int$limit = \fC500\fP, int$fromOrderId = \fC1\fP)"

.PP
orders attempts to get the orders for all or a specific currency $allBNBOrders = $api->orders( 'BNBBTC' );
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$limit\fP int the amount of orders returned 
.br
\fI$fromOrderId\fP string return the orders from this order onwards 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or array of orderDetails array 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 499 of file php-binance-api\&.php\&.
.SS "Binance\\API::orderStatus (string$symbol, $orderid)"

.PP
orderStatus attempts to get orders status $orderid = '123456789'; $order = $api->orderStatus('BNBBTC', $orderid);
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$orderid\fP string the orderid to cancel 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or the order details 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 459 of file php-binance-api\&.php\&.
.SS "Binance\\API::prevDay (string$symbol = \fCnull\fP)"

.PP
prevDay get 24hr ticker price change statistics for symbols $prevDay = $api->prevDay('BNBBTC');
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP (optional) symbol to get the previous day change for 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or array of prevDay change 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 738 of file php-binance-api\&.php\&.
.SS "Binance\\API::prices ()"

.PP
prices get all the current prices $ticker = $api->prices();
.PP
\fBReturns:\fP
.RS 4
array with error message or array of all the currencies prices 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 698 of file php-binance-api\&.php\&.
.SS "Binance\\API::sell (string$symbol, $quantity, $price, string$type = \fC'LIMIT'\fP, array$flags = \fC[]\fP)"

.PP
sell attempts to create a currency order each currency supports a number of order types, such as -LIMIT -MARKET -STOP_LOSS -STOP_LOSS_LIMIT -TAKE_PROFIT -TAKE_PROFIT_LIMIT -LIMIT_MAKER You should check the 
.PP
\fBSee Also:\fP
.RS 4
exchangeInfo for each currency to determine what types of orders can be placed against specific pairs
.RE
.PP
$quantity = 1; $price = 0\&.0005; $order = $api->sell('BNBBTC', $quantity, $price);
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$quantity\fP string the quantity required 
.br
\fI$price\fP string price per unit you want to spend 
.br
\fI$type\fP string type of order 
.br
\fI$flags\fP array addtional options for order type 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or the order details 
.RE
.PP

.PP
Definition at line 345 of file php-binance-api\&.php\&.
.SS "Binance\\API::sellTest (string$symbol, $quantity, $price, string$type = \fC'LIMIT'\fP, array$flags = \fC[]\fP)"

.PP
sellTest attempts to create a TEST currency order 
.PP
\fBSee Also:\fP
.RS 4
sell()
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string the currency symbol 
.br
\fI$quantity\fP string the quantity required 
.br
\fI$price\fP string price per unit you want to spend 
.br
\fI$type\fP array config 
.br
\fI$flags\fP array config 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or empty or the order details 
.RE
.PP

.PP
Definition at line 362 of file php-binance-api\&.php\&.
.SS "Binance\\API::setProxy (array$proxyconf)"

.PP
setProxy set proxy config by passing in an array of the proxy configuration $proxyConf = [ 'proto' => 'tcp', 'address' => '192\&.168\&.1\&.1', 'port' => '8080', 'user' => 'dude', 'pass' => 'd00d' ];
.PP
$api->setProxy( $proxyconf );
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.PP
Definition at line 867 of file php-binance-api\&.php\&.
.SS "Binance\\API::sortDepth (string$symbol, int$limit = \fC11\fP)"

.PP
sortDepth Sorts depth data for display & getting highest bid and lowest ask $sorted = $api->sortDepth($symbol, $limit);
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string to sort 
.br
\fI$limit\fP int depth 
.RE
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.PP
Definition at line 1643 of file php-binance-api\&.php\&.
.SS "Binance\\API::terminate ($endpoint)"

.PP
terminate Terminates websocket endpoints\&. View endpoints first: print_r($api->subscriptions)
.PP
$api->terminate('ethbtc_kline@5m');
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.PP
Definition at line 2002 of file php-binance-api\&.php\&.
.SS "Binance\\API::ticker ($symbol, callable$callback)"

.PP
ticker pulls 24h price change statistics via WebSocket $api->ticker(false, function($api, $symbol, $ticker) { print_r($ticker); });
.PP
\fBParameters:\fP
.RS 4
\fI$symbol\fP string optional symbol or false 
.br
\fI$callback\fP callable closure 
.RE
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.PP
Definition at line 1824 of file php-binance-api\&.php\&.
.SS "Binance\\API::time ()"

.PP
time Gets the server time $time = $api->time();
.PP
\fBReturns:\fP
.RS 4
array with error message or array with server time key 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 559 of file php-binance-api\&.php\&.
.SS "Binance\\API::trades ($symbols, callable$callback)"

.PP
trades Trades WebSocket Endpoint $api->trades(['BNBBTC'], function($api, $symbol, $trades) { echo '{$symbol} trades update'\&.PHP_EOL; print_r($trades); });
.PP
\fBParameters:\fP
.RS 4
\fI$symbols\fP 
.br
\fI$callback\fP callable closure 
.RE
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.PP
Definition at line 1756 of file php-binance-api\&.php\&.
.SS "Binance\\API::userData (&$balance_callback, &$execution_callback = \fCfalse\fP)"

.PP
userData Issues userDataStream token and keepalive, subscribes to userData WebSocket $balance_update = function($api, $balances) { print_r($balances); echo 'Balance update'\&.PHP_EOL; };
.PP
$order_update = function($api, $report) { echo 'Order update'\&.PHP_EOL; print_r($report); $price = $report['price']; $quantity = $report['quantity']; $symbol = $report['symbol']; $side = $report['side']; $orderType = $report['orderType']; $orderId = $report['orderId']; $orderStatus = $report['orderStatus']; $executionType = $report['orderStatus']; if( $executionType == 'NEW' ) { if( $executionType == 'REJECTED' ) { echo 'Order Failed! Reason: {$report['rejectReason']}'\&.PHP_EOL; } echo '{$symbol} {$side} {$orderType} ORDER #{$orderId} ({$orderStatus})'\&.PHP_EOL; echo '\&.\&.price: {$price}, quantity: {$quantity}'\&.PHP_EOL; return; }
.PP
//NEW, CANCELED, REPLACED, REJECTED, TRADE, EXPIRED echo '{$symbol} {$side} {$executionType} {$orderType} ORDER #{$orderId}'\&.PHP_EOL; }; $api->userData($balance_update, $order_update);
.PP
\fBParameters:\fP
.RS 4
\fI$balance_callback\fP callable function 
.br
\fI$execution_callback\fP callable function 
.RE
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 2063 of file php-binance-api\&.php\&.
.SS "Binance\\API::useServerTime ()"

.PP
useServerTime adds the 'useServerTime'=>true to the API request to avoid time errors $api->useServerTime();
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 543 of file php-binance-api\&.php\&.
.SS "Binance\\API::withdraw (string$asset, string$address, $amount, $addressTag = \fCnull\fP)"

.PP
withdraw requests a asset be withdrawn from binance to another wallet $asset = 'BTC'; $address = '1C5gqLRs96Xq4V2ZZAR1347yUCpHie7sa'; $amount = 0\&.2; $response = $api->withdraw($asset, $address, $amount);
.PP
$address = '44tLjmXrQNrWJ5NBsEj2R77ZBEgDa3fEe9GLpSf2FRmhexPvfYDUAB7EXX1Hdb3aMQ9FLqdJ56yaAhiXoRsceGJCRS3Jxkn'; $addressTag = '0e5e38a01058dbf64e53a4333a5acf98e0d5feb8e523d32e3186c664a9c762c1'; $amount = 0\&.1; $response = $api->withdraw($asset, $address, $amount, $addressTag);
.PP
\fBParameters:\fP
.RS 4
\fI$asset\fP string the currency such as BTC 
.br
\fI$address\fP string the addressed to whihc the asset should be deposited 
.br
\fI$amount\fP double the amount of the asset to transfer 
.br
\fI$addressTag\fP string adtional transactionid required by some assets 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or array transaction 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 597 of file php-binance-api\&.php\&.
.SS "Binance\\API::withdrawFee (string$asset)"

.PP
withdrawFee get the withdrawal fee for an asset $withdrawFee = $api->withdrawFee( 'BTC' );
.PP
\fBParameters:\fP
.RS 4
\fI$asset\fP string currency such as BTC 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or array containing withdrawFee 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 681 of file php-binance-api\&.php\&.
.SS "Binance\\API::withdrawHistory (string$asset = \fCnull\fP, array$params = \fC[]\fP)"

.PP
withdrawHistory get the withdrawal history for an asset $withdrawHistory = $api->withdrawHistory();
.PP
$withdrawHistory = $api->withdrawHistory( 'BTC' );
.PP
\fBParameters:\fP
.RS 4
\fI$asset\fP string empty or the currency such as BTC 
.br
\fI$params\fP array optional startTime, endTime, status parameters 
.RE
.PP
\fBReturns:\fP
.RS 4
array with error message or array deposit history information 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\\Exception\fP 
.RE
.PP

.PP
Definition at line 663 of file php-binance-api\&.php\&.
.SH "Member Data Documentation"
.PP 
.SS "Binance\\API::$api_key\fC [protected]\fP"

.PP
Definition at line 34 of file php-binance-api\&.php\&.
.SS "Binance\\API::$api_secret\fC [protected]\fP"

.PP
Definition at line 35 of file php-binance-api\&.php\&.
.SS "Binance\\API::$base = 'https://api\&.binance\&.com/api/'\fC [protected]\fP"

.PP
Definition at line 31 of file php-binance-api\&.php\&.
.SS "Binance\\API::$chartQueue = []\fC [protected]\fP"

.PP
Definition at line 38 of file php-binance-api\&.php\&.
.SS "Binance\\API::$charts = []\fC [protected]\fP"

.PP
Definition at line 39 of file php-binance-api\&.php\&.
.SS "Binance\\API::$curlOpts = []\fC [protected]\fP"

.PP
Definition at line 40 of file php-binance-api\&.php\&.
.SS "Binance\\API::$depthCache = []\fC [protected]\fP"

.PP
Definition at line 36 of file php-binance-api\&.php\&.
.SS "Binance\\API::$depthQueue = []\fC [protected]\fP"

.PP
Definition at line 37 of file php-binance-api\&.php\&.
.SS "Binance\\API::$info\fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
= [
        "timeOffset" => 0
.fi
.PP
Definition at line 41 of file php-binance-api\&.php\&.
.SS "Binance\\API::$proxyConf = null\fC [protected]\fP"

.PP
Definition at line 44 of file php-binance-api\&.php\&.
.SS "Binance\\API::$requestCount = 0\fC [protected]\fP"

.PP
Definition at line 46 of file php-binance-api\&.php\&.
.SS "Binance\\API::$stream = 'wss://stream\&.binance\&.com:9443/ws/'\fC [protected]\fP"

.PP
Definition at line 33 of file php-binance-api\&.php\&.
.SS "Binance\\API::$transfered = 0\fC [protected]\fP"

.PP
Definition at line 45 of file php-binance-api\&.php\&.
.SS "Binance\\API::$wapi = 'https://api\&.binance\&.com/wapi/'\fC [protected]\fP"

.PP
Definition at line 32 of file php-binance-api\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Binance Api from the source code\&.
